apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: hello-kube
          image: fhsinchy/hello-kube
          ports:
            - containerPort: 80
